services:
  scenario-client:
    container_name: scenario-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/appuser/app
      - /home/appuser/app/node_modules
    command: [ "npm", "run", "dev", "--host" ]
